### ISSUE TITLE
Doesn't accept stream for Body

### ISSUE THREAD

**Issue by knownasilya** [trivikr/aws-sdk-js-v3#190]
## Describe the bug
Passing a readable stream to `Body` returns the following error:

```
[ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
    at Function.from (buffer.js:333)
    at getDataReadable (getDataReadable.ts:6)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async getChunkStream (getChunkStream.ts:17)
    at async Upload.__doConcurrentUpload (Upload.ts:121)
    at async Promise.all (index 0)
    at async Upload.__doMultipartUpload (Upload.ts:196)
    at async Upload.done (Upload.ts:88)
    at async S3Service.upload (s3-service.ts:64)
    at async handleRule (process-rule.ts:157)
    at async processRule (process-rule.ts:67)
    at async EventEmitter.<anonymous> (background.html:9)
```

#### SDK version number
```
    "@aws-sdk/client-s3": "^3.30.0",
    "@aws-sdk/lib-storage": "^3.30.0",
```

#### Is the issue in the browser/Node.js/ReactNative?
Node.js Electron

#### Details of the browser/Node.js/ReactNative version
Node v14.17.6

## Steps to reproduce
```js
let stream = Readable.from([ .... ]);
const uploads = new Upload({
  client: this.#client,
  params: {
    Key: key,
    ContentType: `application/json`,
    Bucket,
    Body: stream,
  },
});

uploads.on('httpUploadProgress', (progress) => {
  console.log('S3 Progress:', progress);
});

await uploads.done();
```

**Comment by knownasilya** [comment]
So actually in this case it is closer to

```js

let readable = Readable.from([{...}, {...}]).pipe(stringify());
```

`stringify` comes from https://www.npmjs.com/package/geojson-stream#geojsonstreamstringify

**Comment by knownasilya** [comment]
Ok. It seems I wasn't actually stringifying. But I ran into another issue.

```
ypeError [ERR_INVALID_ARG_TYPE]: The "iterable" argument must be an instance of Iterable. Received an instance of Stream
    at from (internal/streams/from.js:32:11)
    at Function.Readable.from (internal/streams/readable.js:1361:10)
    at S3Service.upload (/Users/iradchenko/workspace/mapgeo-sync/electron-app/dist/s3-service.js:50:41)
    at handleRule (/Users/iradchenko/workspace/mapgeo-sync/electron-app/dist/process-rule.js:84:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async processRule (/Users/iradchenko/workspace/mapgeo-sync/electron-app/dist/process-rule.js:20:28)
    at async EventEmitter.<anonymous> (file:///Users/iradchenko/workspace/mapgeo-sync/electron-app/dist/views/background.html:9:22)
```

The stream passed is a Transform stream, and that's why it fails.
